creation_rules:
  - path_regex: ^configuration/dietpi/secrets/.*\.sops\.env$
    age: >-
      age1s7m0azt3n3y5ygplmsu890yc3gtc9c96qu4epym4c0xr6dsfuqwshpcwjr,age12yrcf9ekgjke2ka8glpn8erq6w6l26dccz7uyahf4lpady74yu2q6dpqzy
